name: Deploy Website

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.VPS_HOST }}        # coogsnation.com OR 66.29.155.208
          username: ${{ secrets.VPS_USER }}      # coogarqd
          password: ${{ secrets.VPS_PASSWORD }}  # your cPanel password
          protocol: ftps
          port: 21
          server-dir: /home/coogarqd/public_html/
